@startuml
  class Alumno{
    - Int idAlumno
    - String nombre
    - String apellido
    - String matricula
    - String carrera
    - String estado_procedencia
    - String disciplina_deportiva
    - String mail_tutor
    - String estatus
    + alta()
    + baja()
    + consulta()
    + asignarHabitacion()
    + contactarAlumno()
  }

  class Habitacion{
    - Int No_habitacion
    - Int capacidad
    + alta()
    + baja()
    + consulta()
  }

  class Calificaciones{
    - String id_materia
    - Float calificacion
    + alta()
    + baja()
    + consulta()
  }

  class PerfilMedico{
    - Int idPerfilMed
    - mediumBlob Archivo
    - String comentarios
    + alta()
    + baja()
    + consulta()
  }

  class PerfilPsicologico{
    - Int idPerfilPsic
    - mediumBlob Archivo
    - String comentarios
    + alta()
    + baja()
    + consulta()
  }

  class RubricaDeEvaluacion{
    - Int idRubrica
    - Fecha_Hora fecha_hora
    + alta()
    + baja()
    + consulta()
  }

  class RubricaDeEvaluacionConcepto{
    - Int idConcepto
    - String descripcion
    - Int porcentaje
    + alta()
    + baja()
    + consulta()
  }

  class Prefectos{
    - String nombre
    - String apellido
    - String nomina
    - String email
    + alta()
    + baja()
    + consulta()
  }

  class Actividades{
    - Fecha_Hora fecha_hora
    - Int id_actividad
    - String Descripcion
    - Bool obligatorio
    + alta()
    + baja()
    + consulta()
  }

  abstract class Reporte{
    # Fecha_Hora fecha_hora
    + alta()
    + baja()
    + consulta()
  }

  class HorasEntrada{
    - Int id_reporte_entrada
    - String comentarios
  }

  class Ausencias{
    - Bool justificada
    - String motivo
    - Int id_reporte_ausencia
  }

  class Visitas{
    - String nombre_visitante
    - Int id_reporte_visitas
  }

  class Indisciplina{
    - String motivo
    - String comentarios
    - Int id_reporte_indisciplina
  }

  Alumno <.. Calificaciones : obtiene

  Alumno <.. Reporte : tiene

  Reporte <|--  Visitas

  Reporte <|--  Ausencias

  Reporte <|--  Indisciplina

  Reporte <|--  HorasEntrada : hereda

  Alumno <.. PerfilPsicologico : tiene

  Alumno <.. PerfilMedico : tiene

  Alumno o-- Habitacion : habita

  Alumno <.. RubricaDeEvaluacion : es evaluado

  Prefectos -->  RubricaDeEvaluacion : Escriben

  Prefectos -->  Actividades : Realizan

  RubricaDeEvaluacion <.. RubricaDeEvaluacionConcepto : compuesta
@enduml
